[package]
name = "simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neural-network = { path = "../neural-network" }

glam = "0.27.0"
itertools = "0.12.1"
