[package]
name = "neural-network-visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
neural-network = { path = "../neural-network" }

clap = { version = "4.5.6", features = ["derive"] }
svg = "0.17.0"
serde_json = "1.0.117"
